### ISSUE TITLE
register Sinatra::Synchrony causing eof

### ISSUE THREAD

**Issue by ungoldman** [kyledrake/sammy_davis_jr#1]
When hitting index on a fresh install, it seems one GET request is registering as several and exploding the server, returning no data. Removing 'register Sinatra::Synchrony' from environment.rb fixes the problem for now... but synchrony is kind of the flagship toy here, right?

https://gist.github.com/1318752

**Comment by zeeshanlakhani** [comment]
Did you ever solve this issue, as I'm having the same problem running in development mode with bundle exec?

**Comment by kyledrake** [comment]
This is probably related to 1.9.3, but I will take a look.

This is an older base, I have a different opinion about a lot of things than this project currently presents. But I will try to sit down and clean it up when I get a chance.

For now I would just recommend disabling Sinatra::Synchrony and using a threaded server like Puma (assuming Puma is stable now.. haven't checked recently). Sinatra::Synchrony is cool but it really is a power tool, I don't recommend it to people anymore unless they are solving a very specific problem.

I've written more about this here: http://kyledrake.net/sinatra-synchrony/#further-reading

**Comment by zeeshanlakhani** [comment]
Thank for the answer and extra resources Kyle. I'll also take a look at puma.

**Comment by ungoldman** [comment]
Hello from the future! This is not an issue anymore.
